package com.example.derek.helloglass;

import android.app.Activity;
import android.content.Context;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.os.StrictMode;
import android.view.View;

import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import org.json.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;

/**
 * Created by Derek on 4/10/2015.
 */
public class JSONtest extends Activity {
    /** {@link com.google.android.glass.widget.CardScrollView} to use as the main content view. */
    private CardScrollView mCardScroller;
    private CardScrollAdapter mAdapter;
    private double latitude, longitude;

    // /* "Hello World!" {@link View} generated by {@link #buildView()}. */
    private View mView;


    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        ArrayList<CardBuilder> cards = new ArrayList<CardBuilder>();
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);
/*
        LocationManager lm = (LocationManager)getSystemService(Context.LOCATION_SERVICE);
        final Location location = lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);

        LocationListener locationListener = new LocationListener() {
            public void onLocationChanged(Location location) {
                // Called when a new location is found by the network location provider.
                latitude = location.getLatitude();
                longitude = location.getLongitude();
            }

            public void onStatusChanged(String provider, int status, Bundle extras) {
            }

            public void onProviderEnabled(String provider) {
            }

            public void onProviderDisabled(String provider) {
            }
        };

        lm.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, locationListener);
*/
        try {
            // http://labs.puneeth.org:5000/techlab/getrestaurants?latitude=39.011870&longitude=-77.527546

            longitude = 39.011870;//location.getLongitude();
            latitude = 77.527546;//location.getLatitude();
            String ur = "http://labs.puneeth.org:5000/techlab/getrestaurants?latitude="+latitude+"&longitude="+longitude;
            URL url = new URL(ur);

            InputStream is = url.openStream();  // throws an IOException

            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String str = "", line = "";
            line = br.readLine();

            while (line != null)
            {
                str += line;
                line = br.readLine();
            }


            JSONArray arr = new JSONArray(str);

            for (int i = 0; i < arr.length(); i++) {
                JSONObject curr = arr.getJSONObject(i);
                cards.add(new CardBuilder(this, CardBuilder.Layout.TEXT).setText( curr.getString("name") ));
            }

        }
        catch(Exception e)
        {
            e.printStackTrace();
            cards.add(new CardBuilder(this, CardBuilder.Layout.TEXT).setText( "EXCEPTION CAUGHT" ));
        }
        mAdapter = new CardAdapter( cards );
        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(mAdapter);
        setContentView(mCardScroller);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.

     private View buildView() {
     CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

     card.setText(R.string.hello_world);
     return card.getView();
     }
     */
}
