package com.example.derek.helloglass;

import android.app.Activity;
import android.os.Bundle;
import android.os.StrictMode;
import android.view.View;

import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import org.json.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;

/**
 * Created by Derek on 4/10/2015.
 */
public class JSONtest extends Activity {
    /** {@link com.google.android.glass.widget.CardScrollView} to use as the main content view. */
    private CardScrollView mCardScroller;
    private CardScrollAdapter mAdapter;

    // /* "Hello World!" {@link View} generated by {@link #buildView()}. */
    private View mView;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        ArrayList<CardBuilder> cards = new ArrayList<CardBuilder>();
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);

        try {
            // http://labs.puneeth.org:5000/techlab/getrestaurants?latitude=39.011870&longitude=-77.527546

            double latitude = 39.011870;
            double longitude = -77.527546;
            String ur = "http://labs.puneeth.org:5000/techlab/getrestaurants?latitude="+latitude+"&longitude="+longitude;
            ur = "http://labs.puneeth.org:5000/techlab/getrestaurants?latitude=39.011870&longitude=-77.527546";
            URL url = new URL(ur);

            InputStream is = url.openStream();  // throws an IOException

            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String str = "", line = "";
            line = br.readLine();

            while (line != null)
            {
                str += line;
                line = br.readLine();
            }


            JSONArray arr = new JSONArray(str);

            for (int i = 0; i < arr.length(); i++) {
                JSONObject curr = arr.getJSONObject(i);
                cards.add(new CardBuilder(this, CardBuilder.Layout.TEXT).setText( curr.getString("name") ));
            }

        }
        catch(Exception e)
        {
            System.out.println("purple");
            e.printStackTrace();
            cards.add(new CardBuilder(this, CardBuilder.Layout.TEXT)
                    .setText("Exception caught"));
        }
        cards.add(new CardBuilder(this, CardBuilder.Layout.TEXT)
                .setText( "default" ));
        mAdapter = new CardAdapter( cards );
        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(mAdapter);
        setContentView(mCardScroller);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.

     private View buildView() {
     CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

     card.setText(R.string.hello_world);
     return card.getView();
     }
     */
}
